name: naratia_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  share_plus: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.1
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#121212"

  android: true
  ios: true

  android_12:
    color: "#121212"

#flutter_launcher_icons:
 # android: "launcher_icon"
  #ios: true
  #image_path: "assets/images/logo_naratia.jpeg"
  #adaptive_icon_background: "#02040F" 
  #adaptive_icon_foreground: "assets/images/logo_naratia.jpeg"